// playerNames.ts

export const soccerPlayers = [
    
  'Lionel Messi',
'Cristiano Ronaldo',
'Kylian Mbappé',
'Erling Haaland',
'Neymar Jr.',
'Kevin De Bruyne',
'Karim Benzema',
'Mohamed Salah',
'Robert Lewandowski',
'Vinícius Júnior',
'Luka Modrić',
'Alisson Becker',
'Sadio Mané',
'Harry Kane',
'Rúben Dias',
'Jude Bellingham',
'Son Heung-min',
'Gavi',
'Pedri',
'Declan Rice',
'Bruno Fernandes',
'Thomas Müller',
'Angel Di Maria',
'Joshua Kimmich',
'Frenkie de Jong',
'Achraf Hakimi',
'Germán Pezzella',
'Christian Pulisic',
'Raheem Sterling',
'Marcus Rashford',
'Martin Ødegaard',
'Romelu Lukaku',
'N Golo Kanté',
'Giorgio Chiellini',
'Thibaut Courtois',
'Sergio Ramos',
'Virgil van Dijk',
'Antoine Griezmann',
'David de Gea',
'Yannick Carrasco',
'Ederson Moraes',
'Emile Smith Rowe',
'Jack Grealish',
'Toni Kroos',
'César Azpilicueta',
'David Alaba',
'Riyad Mahrez',
'Kai Havertz',
'Leon Goretzka',
'João Félix',
'Dusan Tadic',
'Pedro Neto',
'Gerard Moreno',
'Christian Romero',
'Marco Verratti',
'David Silva',
'Wilfried Zaha',
'Ousmane Dembélé',
'Pau Torres',
'Hakim Ziyech',
'Dani Carvajal',
'Memphis Depay',
'Nicolas Pépé',
'Diogo Jota',
'Benjamin Pavard',
'David Brooks',
'Rafael Leão',
'Andreas Christensen',
'Alexander Isak',
'Nuno Mendes',
'Jadon Sancho',
'Milan Škriniar',
'Lucas Paquetá',
'Jonathan David',
'Fikayo Tomori',
'Youri Tielemans',
'Ismaël Bennacer',
'Declan Rice',
'Nicolas Otamendi',
'Sergio Busquets',
'Wojciech Szczęsny',
'Callejón',
'Gonzalo Higuain',
'Alvaro Morata',
'Pablo Sarabia',
'Christian Eriksen',
'Marcelo',
'Fabinho',
'Bruno Guimarães',
'Alexis Sánchez',
'Iñaki Williams',
'Nico Williams',
'Angelino',
'Dani Olmo',
'Victor Osimhen',
'Claudio Marchisio',
'Lorenzo Insigne',
'Diego Jota',
'Fabian Ruiz',
'Reece James',
'Sandro Tonali',
'Pietro Pellegri',
'Stefan de Vrij',
'Frenkie de Jong',
'Jasper Cillessen',
'Jannik Sinner',
'Kasper Schmeichel',
'Leandro Paredes',
'Edin Dzeko',
'Bruno Peres',
'Timo Werner',
'Teun Koopmeiners',
'Nico Schulz',
'David Neres',
'Henrikh Mkhitaryan',
'Milan Škriniar',
'Pedro',
'Victor Lindelöf',
'Youssef En-Nesyri',
'Alfonso Pedraza',
'Konstantinos Tsimikas',
'Robin Gosens',
'Matthijs de Ligt',
'Nico Elvedi',
'Dominik Szoboszlai',
'Daniil Medvedev',
'Maxi Gómez',
'Rodrygo Goes',
'Sergio Canales',
'Dani Olmo',
'Juan Mata',
'Victor Ruiz',
'Bruno Guimarães',
'Edin Džeko',
'Danilo Pereira',
'Cody Gakpo',
'Dani Carvajal',
'Rafael Tolói',
'Giorgio Chiellini',
'Ollie Watkins',
'Rasmus Højlund',
'Vitor Roque',
'Julian Brandt',
'Salvatore Sirigu',
'Ben White',
'Malcolm',
'Alfredo Morelos',
'Sergio Herrera',
'Victor Osimhen',
'Ruben Loftus-Cheek',
'Lionel', 'Messi',
'Cristiano', 'Ronaldo',
'Kylian', 'Mbappé',
'Erling', 'Haaland',
'Neymar', 'Jr.',
'Kevin', 'De Bruyne',
'Karim', 'Benzema',
'Mohamed', 'Salah',
'Robert', 'Lewandowski',
'Vinícius', 'Júnior',
'Luka', 'Modrić',
'Alisson', 'Becker',
'Sadio', 'Mané',
'Harry', 'Kane',
'Rúben', 'Dias',
'Jude', 'Bellingham',
'Son', 'Heung-min',
'Gavi', '',
'Pedri', '',
'Declan', 'Rice',
'Bruno', 'Fernandes',
'Thomas', 'Müller',
'Angel', 'Di Maria',
'Joshua', 'Kimmich',
'Frenkie', 'de Jong',
'Achraf', 'Hakimi',
'Germán', 'Pezzella',
'Christian', 'Pulisic',
'Raheem', 'Sterling',
'Marcus', 'Rashford',
'Martin', 'Ødegaard',
'Romelu', 'Lukaku',
'N Golo', 'Kanté',
'Giorgio', 'Chiellini',
'Thibaut', 'Courtois',
'Sergio', 'Ramos',
'Virgil', 'van Dijk',
'Antoine', 'Griezmann',
'David', 'de Gea',
'Yannick', 'Carrasco',
'Ederson', 'Moraes',
'Emile', 'Smith Rowe',
'Jack', 'Grealish',
'Toni', 'Kroos',
'César', 'Azpilicueta',
'David', 'Alaba',
'Riyad', 'Mahrez',
'Kai', 'Havertz',
'Leon', 'Goretzka',
'João', 'Félix',
'Dusan', 'Tadic',
'Pedro', 'Neto',
'Gerard', 'Moreno',
'Christian', 'Romero',
'Marco', 'Verratti',
'David', 'Silva',
'Wilfried', 'Zaha',
'Ousmane', 'Dembélé',
'Pau', 'Torres',
'Hakim', 'Ziyech',
'Dani', 'Carvajal',
'Memphis', 'Depay',
'Nicolas', 'Pépé',
'Diogo', 'Jota',
'Benjamin', 'Pavard',
'David', 'Brooks',
'Rafael', 'Leão',
'Andreas', 'Christensen',
'Alexander', 'Isak',
'Nuno', 'Mendes',
'Jadon', 'Sancho',
'Milan', 'Škriniar',
'Lucas', 'Paquetá',
'Jonathan', 'David',
'Fikayo', 'Tomori',
'Youri', 'Tielemans',
'Ismaël', 'Bennacer',
'Declan', 'Rice',
'Nicolas', 'Otamendi',
'Sergio', 'Busquets',
'Wojciech', 'Szczęsny',
'Callejón', '',
'Gonzalo', 'Higuain',
'Alvaro', 'Morata',
'Pablo', 'Sarabia',
'Christian', 'Eriksen',
'Marcelo', '',
'Fabinho', '',
'Bruno', 'Guimarães',
'Alexis', 'Sánchez',
'Iñaki', 'Williams',
'Nico', 'Williams',
'Angelino', '',
'Dani', 'Olmo',
'Victor', 'Osimhen',
'Claudio', 'Marchisio',
'Lorenzo', 'Insigne',
'Diego', 'Jota',
'Fabian', 'Ruiz',
'Reece', 'James',
'Sandro', 'Tonali',
'Pietro', 'Pellegri',
'Stefan', 'de Vrij',
'Frenkie', 'de Jong',
'Jasper', 'Cillessen',
'Jannik', 'Sinner',
'Kasper', 'Schmeichel',
'Leandro', 'Paredes',
'Edin', 'Dzeko',
'Bruno', 'Peres',
'Timo', 'Werner',
'Teun', 'Koopmeiners',
'Nico', 'Schulz',
'David', 'Neres',
'Henrikh', 'Mkhitaryan',
'Milan', 'Škriniar',
'Pedro', '',
'Victor', 'Lindelöf',
'Youssef', 'En-Nesyri',
'Alfonso', 'Pedraza',
'Konstantinos', 'Tsimikas',
'Robin', 'Gosens',
'Matthijs', 'de Ligt',
'Nico', 'Elvedi',
'Dominik', 'Szoboszlai',
'Daniil', 'Medvedev',
'Maxi', 'Gómez',
'Rodrygo', 'Goes',
'Sergio', 'Canales',
'Dani', 'Olmo',
'Juan', 'Mata',
'Victor', 'Ruiz',
'Bruno', 'Guimarães',
'Edin', 'Džeko',
'Danilo', 'Pereira',
'Cody', 'Gakpo',
'Dani', 'Carvajal',
'Rafael', 'Tolói',
'Giorgio', 'Chiellini',
'Ollie', 'Watkins',
'Rasmus', 'Højlund',
'Vitor', 'Roque',
'Julian', 'Brandt',
'Salvatore', 'Sirigu',
'Ben', 'White',
'Malcolm', '',
'Alfredo', 'Morelos',
'Sergio', 'Herrera',
'Victor', 'Osimhen',
'Ruben', 'Loftus-Cheek',
'Real Madrid',
'FC Barcelona',
'Atlético Madrid',
'Sevilla',
'Real Betis',
'Real Sociedad',
'Athletic Bilbao',
'Villarreal',
'Celta Vigo',
'Valencia',
'Osasuna',
'Getafe',
'Granada',
'Alavés',
'Rayo Vallecano',
'Mallorca',
'Cádiz',
'Espanyol',
'Levante',
'Elche',
'Arsenal',
'Aston Villa',
'Bournemouth',
'Brentford',
'Brighton & Hove Albion',
'Burnley',
'Chelsea',
'Crystal Palace',
'Everton',
'Fulham',
'Liverpool',
'Luton Town',
'Manchester City',
'Manchester United',
'Newcastle United',
'Nottingham Forest',
'Sheffield United',
'Tottenham Hotspur',
'West Ham United',
'Wolverhampton Wanderers',
'la liga',
'bundesliga',
'Premier League',
'Arsenal',
'Atlético Madrid',
'Barcelona',
'Bayern Munich',
'Borussia Dortmund',
'FC Porto',
'Inter Milan',
'Juventus',
'Liverpool',
'Manchester City',
'Manchester United',
'Napoli',
'Paris Saint-Germain',
'Real Madrid',
'RB Leipzig',
'Sevilla',
'Tottenham Hotspur',
'Benfica',
'AC Milan',
'Celtic',
'Champions League',

  ];
  
  export const cricketPlayers = [
   'Sachin Tendulkar', 
   'Virat Kohli',
    'Ricky Ponting', 
   'Brian Lara', 
   'Jacques Kallis', 
   'MS Dhoni', 
   'AB de Villiers',
    'Kumar Sangakkara',
     'Muttiah Muralitharan', 
     'Shane Warne', 
    'Glenn McGrath',
     'Wasim Akram', 
     'Sir Vivian Richards',
    'Imran Khan', 
    'Rahul Dravid',
     'Allan Border', 
     'Adam Gilchrist',
     'Sir Ian Botham',
      'Steve Waugh', 
      'Javed Miandad', 
      'Shoaib Akhtar',
      'Brett Lee', 
      'Anil Kumble', 
      'Michael Clarke', 
      'Hashim Amla', 
      'Kevin Pietersen',
       'Alastair Cook', 
       'Dale Steyn', 
      'Shakib Al Hasan',
       'Rohit Sharma', 
       'Yuvraj Singh',
      'Saeed Anwar', 
      'Chris Gayle', 
      'Sunil Gavaskar', 
      'Inzamam-ul-Haq',
       'Lasith Malinga', 
       'Andrew Flintoff',
      'James Anderson', 
      'Graeme Smith', 
      'Kane Williamson', 
      'Brendon McCullum',
       'Ben Stokes', 
       'Joe Root', 
      'Ravichandran Ashwin', 
      'Jasprit Bumrah',
       'Nathan Lyon',
       'Ravindra Jadeja', 
       'Mitchell Starc', 
       'Pat Cummins',
       
       'Trent Boult',
        'Faf du Plessis', 
        'David Warner', 
       'Mohammad Amir', 
       'Shikhar Dhawan',
        'Dwayne Bravo', 
       'Kieron Pollard', 
       'Jason Holder', 
       'Jos Buttler', 
       'Eoin Morgan', 
       'Quinton de Kock', 
       'Mahela Jayawardene',
        'Angelo Mathews', 
        'Mohammed Shami', 
        'Zaheer Khan',
         'Shaun Pollock', 
         'Sanath Jayasuriya', 
         'Shoaib Malik',
         
         'Shai Hope', 
         'Tim Southee', 
         'Stuart Broad', 
         'Ross Taylor', 
         'Dinesh Karthik',
          'Rishabh Pant',
           'Babar Azam', 
         'Mohammad Rizwan', 
         'Kagiso Rabada', 
         'KL Rahul', 
         'Shubman Gill', 
         'Suryakumar Yadav', 
         'Trent Johnston',
          'Tamim Iqbal', 'Mushfiqur Rahim', 'Rashid Khan',
           'Mohammad Nabi', 'Ebadot Hossain', 'Sikandar Raza', 
           'Paul Stirling', 'Kyle Coetzer', 'Mark Wood', 
           'Alex Hales', 'Haris Rauf', 'Fakhar Zaman',
            'Shaheen Afridi', 'Usman Khawaja', 'Marnus Labuschagne',
             'Tim Paine', 'Shardul Thakur', 'Moeen Ali', 'Ruturaj Gaikwad', 'Cameron Green',
  'Sachin', 'Tendulkar', 'Virat', 'Kohli', 'Ricky', 'Ponting', 'Brian', 'Lara', 'Jacques', 'Kallis', 'MS', 'Dhoni', 'AB', 'de Villiers', 'Kumar', 'Sangakkara', 'Muttiah', 'Muralitharan', 'Shane', 'Warne', 'Glenn', 'McGrath', 'Wasim', 'Akram', 'Vivian', 'Richards', 'Imran', 'Khan', 'Rahul', 'Dravid', 'Allan', 'Border', 'Adam', 'Gilchrist', 'Ian', 'Botham', 'Steve', 'Waugh', 'Javed', 'Miandad', 'Shoaib', 'Akhtar', 'Brett', 'Lee', 'Anil', 'Kumble', 'Michael', 'Clarke', 'Hashim', 'Amla', 'Kevin', 'Pietersen', 'Alastair', 'Cook', 'Dale', 'Steyn', 'Shakib', 'Al Hasan', 'Rohit', 'Sharma', 'Yuvraj', 'Singh', 'Saeed', 'Anwar', 'Chris', 'Gayle', 'Sunil', 'Gavaskar', 'Inzamam', 'ul-Haq', 'Lasith', 'Malinga', 'Andrew', 'Flintoff', 'James', 'Anderson', 'Graeme', 'Smith', 'Kane', 'Williamson', 'Brendon', 'McCullum', 'Ben', 'Stokes', 'Joe', 'Root', 'Ravichandran', 'Ashwin', 'Jasprit', 'Bumrah', 'Nathan', 'Lyon', 'Ravindra', 'Jadeja', 'Mitchell', 'Starc', 'Pat', 'Cummins', 'Trent', 'Boult', 'Faf', 'du Plessis', 'David', 'Warner', 'Mohammad', 'Amir', 'Shikhar', 'Dhawan', 'Dwayne', 'Bravo', 'Kieron', 'Pollard', 'Jason', 'Holder', 'Jos', 'Buttler', 'Eoin', 'Morgan', 'Quinton', 'de Kock', 'Mahela', 'Jayawardene', 'Angelo', 'Mathews', 'Mohammed', 'Shami', 'Zaheer', 'Khan', 'Shaun', 'Pollock', 'Sanath', 'Jayasuriya', 'Shoaib', 'Malik', 'Shai', 'Hope', 'Tim', 'Southee', 'Stuart', 'Broad', 'Ross', 'Taylor', 'Dinesh', 'Karthik', 'Rishabh', 'Pant', 'Babar', 'Azam', 'Mohammad', 'Rizwan', 'Kagiso', 'Rabada', 'KL', 'Rahul', 'Shubman', 'Gill', 'Suryakumar', 'Yadav', 'Trent', 'Johnston', 'Tamim', 'Iqbal', 'Mushfiqur', 'Rahim', 'Rashid', 'Khan', 'Mohammad', 'Nabi', 'Ebadot', 'Hossain',
  'Afghanistan', 'Afghanistan Cricket Board',
'Australia', 
'Cricket Australia',
'Bangladesh', 
'Bangladesh Cricket Board',
'England', 
'England and Wales Cricket Board',
'India', 
'Board of Control for Cricket in India',
'Ireland', 
'Cricket Ireland',
'New Zealand', 
'New Zealand Cricket',
'Pakistan', 
'Pakistan Cricket Board',
'South Africa', 
'Cricket South Africa',
'Sri Lanka',
 'Sri Lanka Cricket',
'West Indies', 
'Cricket West Indies',
'Zimbabwe',
 'Zimbabwe Cricket',
'Nepal',
 'Cricket Association of Nepal',
'Scotland', 'Cricket Scotland',
// 'USA', 
'United States of America Cricket Association',
// 'UAE', 
'Emirates Cricket Board',
// 'Afghanistan', 
// 'ACB',
'Australia', 
// 'CA',
'Bangladesh',
//  'BCB',
'England',
//  'ECB',
'India', 'BCCI',
// // 'Ireland', 'CI',
// 'New Zealand', 'NZC',
// 'Pakistan', 'PCB',
// 'South Africa', 'CSA',
// 'Sri Lanka', 'SLC',
// 'West Indies', 'CWI',
// 'Zimbabwe', 'ZC',
// 'Nepal', 'CAN',
// // 'Scotland', 'CS',
// 'USA', 'USACA',
// 'UAE', 'ECB',
];
  
  export const tennisPlayers = [
   'Novak Djokovic',
 'Carlos Alcaraz',
'Daniil Medvedev',
'Rafael Nadal',
'Jannik Sinner',
'Andrey Rublev',
'Stefanos Tsitsipas',
'Alexander Zverev',
'Holger Rune',
'Felix Auger-Aliassime',
'Taylor Fritz',
'Casper Ruud',
'Cameron Norrie',
'Hubert Hurkacz',
'Diego Schwartzman',
'Denis Shapovalov',
'Marin Cilic',
'Nick Kyrgios',
'Grigor Dimitrov',
'Roberto Bautista Agut',
'Jérémy Chardy',
'Aslan Karatsev',
'Lorenzo Sonego',
'Alex de Minaur',
'Reilly Opelka',
'Frances Tiafoe',
'David Goffin',
'Fabio Fognini',
'Botic van de Zandschulp',
'John Isner',
'Filip Krajinovic',
'Tallon Griekspoor',
'Tommy Paul',
'Jack Draper',
'Laslo Djere',
'Adrian Mannarino',
'Miomir Kecmanovic',
'Alexei Popyrin',
'Sam Querrey',
'Borna Coric',
'Lloyd Harris',
'Alejandro Davidovich Fokina',
'Ugo Humbert',
'Benoit Paire',
'Maxime Cressy',
'Emil Ruusuvuori',
'Sebastian Korda',
'Jack Sock',
'Jordan Thompson',
'Pedro Martinez',
'Kyle Edmund',
'Thomas Fabbiano',
'John Millman',
'Dusan Lajovic',
'Marcos Giron',
'Daniel Evans',
'Alejandro Tabilo',
'Mikael Ymer',
'Jiri Vesely',
'Nicolas Jarry',
'Hugo Gaston',
'Luca Van Assche',
'Kamil Majchrzak',
'Gregoire Barrere',
'Sebastian Baez',
'Juan Manuel Cerundolo',
'Hugo Grenier',
'Bernabe Zapata Miralles',
'Max Purcell',
'Alex Molcan',
'Jozef Kovalik',
'Roman Safiullin',
'Tommy Paul',
'Ryan Peniston',
'Nikoloz Basilashvili',
'Diego Schwartzman',
'Marin Cilic',
'Jannik Sinner',
'Dan Evans',
'Jack Sock',
'Dominic Thiem',
'Alexander Bublik',
'Andreas Seppi',
'Pablo Carreño Busta',
'Matteo Berrettini',
'Stefanos Tsitsipas',
'Andrey Rublev',
'Karen Khachanov',
'Diego Schwartzman',
'Lorenzo Sonego',
'Denis Shapovalov',
'Yannick Hanfmann',
'Alexander Zverev',
'Fabio Fognini',
'Reilly Opelka',
'Jared Donaldson',
'Lucas Pouille',
'Hugo Gaston',
'Pablo Andujar',
'Aljaz Bedene',
'Novak', 'Djokovic',
'Carlos', 'Alcaraz',
'Daniil', 'Medvedev',
'Rafael', 'Nadal',
'Jannik', 'Sinner',
'Andrey', 'Rublev',
'Stefanos', 'Tsitsipas',
'Alexander', 'Zverev',
'Holger', 'Rune',
'Felix', 'Auger-Aliassime',
'Taylor', 'Fritz',
'Casper', 'Ruud',
'Cameron', 'Norrie',
'Hubert', 'Hurkacz',
'Diego', 'Schwartzman',
'Denis', 'Shapovalov',
'Marin', 'Cilic',
'Nick', 'Kyrgios',
'Grigor', 'Dimitrov',
'Roberto', 'Bautista Agut',
'Jérémy', 'Chardy',
'Aslan', 'Karatsev',
'Lorenzo', 'Sonego',
'Alex', 'de Minaur',
'Reilly', 'Opelka',
'Frances', 'Tiafoe',
'David', 'Goffin',
'Fabio', 'Fognini',
'Botic', 'van de Zandschulp',
'John', 'Isner',
'Filip', 'Krajinovic',
'Tallon', 'Griekspoor',
'Tommy', 'Paul',
'Jack', 'Draper',
'Laslo', 'Djere',
'Adrian', 'Mannarino',
'Miomir', 'Kecmanovic',
'Alexei', 'Popyrin',
'Sam', 'Querrey',
'Borna', 'Coric',
'Lloyd', 'Harris',
'Alejandro', 'Davidovich Fokina',
'Ugo', 'Humbert',
'Benoit', 'Paire',
'Maxime', 'Cressy',
'Emil', 'Ruusuvuori',
'Sebastian', 'Korda',
'Jack', 'Sock',
'Jordan', 'Thompson',
'Pedro', 'Martinez',
'Kyle', 'Edmund',
'Thomas', 'Fabbiano',
'John', 'Millman',
'Dusan', 'Lajovic',
'Marcos', 'Giron',
'Daniel', 'Evans',
'Alejandro', 'Tabilo',
'Mikael', 'Ymer',
'Jiri', 'Vesely',
'Nicolas', 'Jarry',
'Hugo', 'Gaston',
'Luca', 'Van Assche',
'Kamil', 'Majchrzak',
'Gregoire', 'Barrere',
'Sebastian', 'Baez',
'Juan', 'Manuel Cerundolo',
'Hugo', 'Grenier',
'Bernabe', 'Zapata Miralles',
'Max', 'Purcell',
'Alex', 'Molcan',
'Jozef', 'Kovalik',
'Roman', 'Safiullin',
'Tommy', 'Paul',
'Ryan', 'Peniston',
'Nikoloz', 'Basilashvili',
'Diego', 'Schwartzman',
'Marin', 'Cilic',
'Jannik', 'Sinner',
'Dan', 'Evans',
'Jack', 'Sock',
'Dominic', 'Thiem',
'Alexander', 'Bublik',
'Andreas', 'Seppi',
'Pablo', 'Carreño Busta',
'Matteo', 'Berrettini',
'Stefanos', 'Tsitsipas',
'Andrey', 'Rublev',
'Karen', 'Khachanov',
'Diego', 'Schwartzman',
'Lorenzo', 'Sonego',
'Denis', 'Shapovalov',
'Yannick', 'Hanfmann',
'Alexander', 'Zverev',
'Fabio', 'Fognini',
'Reilly', 'Opelka',
'Jared', 'Donaldson',
'Lucas', 'Pouille',
'Hugo', 'Gaston',
'Pablo', 'Andujar',
'Aljaz', 'Bedene',
'Australian Open', 'Melbourne Park',
'French Open', 'Roland Garros',
'Wimbledon', 'All England Club',
'US Open', 'USTA Billie Jean King National Tennis Center',
'ATP Finals', 'Pala Alpitour',
'WTA Finals', 'Coco-Cola Arena',
'Davis Cup', 'Varies by host country',
'Fed Cup', 'Varies by host country',
'Olympic Games', 'Varies by host city',
'Hopman Cup', 'RAC Arena',
'Laver Cup', 'Varies by host city',
'Masters 1000', 'Varies by event',
'ATP Tour 500', 'Varies by event',
'WTA 500', 'Varies by event',
'Challenger Tour', 'Varies by event',
'ITF World Tennis Tour', 'Varies by event',
'Next Gen ATP Finals', 'PalaLido',
'Junior Grand Slams', 'Varies by event',
'Mixed Doubles Grand Slams', 'Varies by event',
'Doubles Masters 1000', 'Varies by event',
  ];
  